### ISSUE TITLE
compile gradle

### ISSUE THREAD

**Issue by charliee22** [ajbrown/name-machine#6]
Hi,

getting this error when I sync!

dependencies {
    compile 'org.ajbrown:NameMachine:0.1.1'
}

Error:Failed to resolve: org.ajbrown:NameMachine:0.1.1

**Comment by ajbrown** [comment]
Hi @charliee22.  Are you including the repository block?

As of 1.0.0 release (which I just drafted), this will be published to maven central instead of jcenter.  I just uploaded the release, so please give it an hour or so to sync with central, then update your dependency to `org.ajbrown:name-machine:1.0.0`.  I've updated the README to reflect this.

I'm going to close this issue in anticipation of it being resolved once you switch to the maven central release. If you continue to have issues, just reopen it.

Thanks!

**Comment by charliee22** [comment]
thank you! is working like a charm
